name: pushEvents
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: install node Js
              uses: actions/setup-node@v3
              with:
                node-version: 16
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
    Build:
        runs-on: ubuntu-latest
        steps:
          - name: Run Tests
            run: npm test
          - name: npm run build
            run: npm run build   
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              run: echo "DEploying ..."